### ISSUE TITLE
never used github se be kind with me , i have no idea what im doing haha

### ISSUE THREAD

**Issue by romixoo** [letsdoautomation/windows-configuration-designer#1]
im here from the comment on youtube , i dont want to upload code elsewhere so im just doing it here . i edit code when im free and most of the time make many mistakes , but hey we learn from mistakes. 
1. first thing i do is create new win machine and enter audit mode install updates and office then sysprep it and final step to capture the image with dism and create an iso , it can take some time but now that ive mastered it ist so easy , i do this most likely once a month when windows get cumulative updates with in my case clean install many celeron laptop is much worth it to make the iso with updates in it.
2. down below i will upload the files i have edited , feel free to contact me and make changes , i want it to make it work better for me and for other people also 

[1.bat.txt](https://github.com/letsdoautomation/windows-configuration-designer/files/13678216/1.bat.txt)
[activator_debloat.txt](https://github.com/letsdoautomation/windows-configuration-designer/files/13678217/activator_debloat.txt)
[install.txt](https://github.com/letsdoautomation/windows-configuration-designer/files/13678218/install.txt)
[install_software.ps1.txt](https://github.com/letsdoautomation/windows-configuration-designer/files/13678219/install_software.ps1.txt)
[setup.ps1.txt](https://github.com/letsdoautomation/windows-configuration-designer/files/13678220/setup.ps1.txt)

**Comment by romixoo** [comment]
renamed some files to .txt becouse i cant upload them as they are

**Comment by letsdoautomation** [comment]
do you use discord ? if yes you can add me letsdoautomation_49628

**Comment by romixoo** [comment]
request send
