### ISSUE TITLE
No Reboot after applying PPKG

### ISSUE THREAD

**Issue by chstrahm** [letsdoautomation/windows-configuration-designer#2]
I have created a PPKG following your examples listed here. I apply the ppkg, setup.ps1 moves all of the installation files to the correct locations.  The local admin account is created but then nothing happens.  No reboot and the software installation never kicks off.  Not sure if you are able to point me in the right direction or not but thank you.

**Comment by letsdoautomation** [comment]
are you using discord ? if yes then can you maybe join channel https://discord.gg/jsVtn5CMxC ? It will be easier for me to help in there
